export interface City {
  id: string;
  name: string;
  province: string;
}

export interface RouteSegment {
  type: "train" | "bus" | "metro" | "flight";
  from: string;
  to: string;
  departure: string;
  arrival: string;
  duration: string;
  name: string;
  price: string;
}

export interface TransitRoute {
  id: string;
  fromCity: string;
  toCity: string;
  type: "direct" | "transfer";
  segments: RouteSegment[];
  totalDuration: string;
  totalPrice: string;
  tags: string[];
}

export const CITIES: City[] = [
  { id: "beijing", name: "北京", province: "北京市" },
  { id: "shanghai", name: "上海", province: "上海市" },
  { id: "guangzhou", name: "广州", province: "广东省" },
  { id: "shenzhen", name: "深圳", province: "广东省" },
  { id: "chengdu", name: "成都", province: "四川省" },
  { id: "hangzhou", name: "杭州", province: "浙江省" },
  { id: "wuhan", name: "武汉", province: "湖北省" },
  { id: "xian", name: "西安", province: "陕西省" },
  { id: "nanjing", name: "南京", province: "江苏省" },
  { id: "chongqing", name: "重庆", province: "重庆市" },
  { id: "tianjin", name: "天津", province: "天津市" },
  { id: "suzhou", name: "苏州", province: "江苏省" },
  { id: "zhengzhou", name: "郑州", province: "河南省" },
  { id: "changsha", name: "长沙", province: "湖南省" },
  { id: "kunming", name: "昆明", province: "云南省" },
  { id: "harbin", name: "哈尔滨", province: "黑龙江省" },
  { id: "dalian", name: "大连", province: "辽宁省" },
  { id: "qingdao", name: "青岛", province: "山东省" },
  { id: "jinan", name: "济南", province: "山东省" },
  { id: "nanchang", name: "南昌", province: "江西省" },
  { id: "fuzhou", name: "福州", province: "福建省" },
  { id: "xiamen", name: "厦门", province: "福建省" },
  { id: "wuxi", name: "无锡", province: "江苏省" },
  { id: "dongguan", name: "东莞", province: "广东省" },
  { id: "zhuhai", name: "珠海", province: "广东省" },
  { id: "zhongshan", name: "中山", province: "广东省" },
  { id: "shantou", name: "汕头", province: "广东省" },
  { id: "wenzhou", name: "温州", province: "浙江省" },
  { id: "ningbo", name: "宁波", province: "浙江省" },
  { id: "jiaxing", name: "嘉兴", province: "浙江省" },
  { id: "huaian", name: "淮安", province: "江苏省" },
  { id: "changzhou", name: "常州", province: "江苏省" },
  { id: "nantong", name: "南通", province: "江苏省" },
  { id: "yangzhou", name: "扬州", province: "江苏省" },
  { id: "taizhou", name: "泰州", province: "江苏省" },
  { id: "jiangyin", name: "江阴", province: "江苏省" },
  { id: "ruian", name: "瑞安", province: "浙江省" },
  { id: "cangzhou", name: "沧州", province: "河北省" },
  { id: "baoding", name: "保定", province: "河北省" },
  { id: "tangshan", name: "唐山", province: "河北省" },
  { id: "shenyang", name: "沈阳", province: "辽宁省" },
  { id: "siping", name: "四平", province: "吉林省" },
  { id: "anqing", name: "安庆", province: "安徽省" },
  { id: "wuhu", name: "芜湖", province: "安徽省" },
  { id: "benxi", name: "本溪", province: "辽宁省" },
  { id: "zhangzhou", name: "漳州", province: "福建省" },
  { id: "chaozhou", name: "潮州", province: "广东省" },
  { id: "haikou", name: "海口", province: "海南省" },
  { id: "lanzhou", name: "兰州", province: "甘肃省" },
];

export const SAMPLE_ROUTES: TransitRoute[] = [
  {
    id: "bj-sh-1",
    fromCity: "北京",
    toCity: "上海",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "北京南站",
        to: "上海虹桥站",
        departure: "06:30",
        arrival: "11:02",
        duration: "4小时32分",
        name: "G1 复兴号",
        price: "¥553",
      },
    ],
    totalDuration: "4小时32分",
    totalPrice: "¥553",
    tags: ["高铁直达", "最快"],
  },
  {
    id: "bj-sh-2",
    fromCity: "北京",
    toCity: "上海",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "北京南站",
        to: "上海虹桥站",
        departure: "08:00",
        arrival: "12:38",
        duration: "4小时38分",
        name: "G5 复兴号",
        price: "¥553",
      },
    ],
    totalDuration: "4小时38分",
    totalPrice: "¥553",
    tags: ["高铁直达"],
  },
  {
    id: "bj-sh-3",
    fromCity: "北京",
    toCity: "上海",
    type: "direct",
    segments: [
      {
        type: "bus",
        from: "北京六里桥客运站",
        to: "上海长途客运总站",
        departure: "18:00",
        arrival: "次日 06:30",
        duration: "12小时30分",
        name: "长途卧铺巴士",
        price: "¥280",
      },
    ],
    totalDuration: "12小时30分",
    totalPrice: "¥280",
    tags: ["长途巴士", "经济"],
  },
  {
    id: "bj-sh-4",
    fromCity: "北京",
    toCity: "上海",
    type: "direct",
    segments: [
      {
        type: "flight",
        from: "北京首都机场",
        to: "上海浦东机场",
        departure: "07:00",
        arrival: "09:20",
        duration: "2小时20分",
        name: "CA1885",
        price: "¥890",
      },
    ],
    totalDuration: "2小时20分",
    totalPrice: "¥890",
    tags: ["飞机", "最快"],
  },
  {
    id: "bj-gz-1",
    fromCity: "北京",
    toCity: "广州",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "北京西站",
        to: "广州南站",
        departure: "07:26",
        arrival: "15:26",
        duration: "8小时00分",
        name: "G71 复兴号",
        price: "¥862",
      },
    ],
    totalDuration: "8小时00分",
    totalPrice: "¥862",
    tags: ["高铁直达"],
  },
  {
    id: "bj-gz-2",
    fromCity: "北京",
    toCity: "广州",
    type: "direct",
    segments: [
      {
        type: "flight",
        from: "北京大兴机场",
        to: "广州白云机场",
        departure: "08:00",
        arrival: "11:20",
        duration: "3小时20分",
        name: "CZ3116",
        price: "¥1080",
      },
    ],
    totalDuration: "3小时20分",
    totalPrice: "¥1080",
    tags: ["飞机", "最快"],
  },
  {
    id: "bj-sz-1",
    fromCity: "北京",
    toCity: "深圳",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "北京西站",
        to: "深圳北站",
        departure: "07:00",
        arrival: "15:06",
        duration: "8小时06分",
        name: "G79 复兴号",
        price: "¥944",
      },
    ],
    totalDuration: "8小时06分",
    totalPrice: "¥944",
    tags: ["高铁直达"],
  },
  {
    id: "bj-cd-1",
    fromCity: "北京",
    toCity: "成都",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "北京西站",
        to: "成都东站",
        departure: "07:00",
        arrival: "14:58",
        duration: "7小时58分",
        name: "G89 复兴号",
        price: "¥778",
      },
    ],
    totalDuration: "7小时58分",
    totalPrice: "¥778",
    tags: ["高铁直达"],
  },
  {
    id: "bj-cd-2",
    fromCity: "北京",
    toCity: "成都",
    type: "direct",
    segments: [
      {
        type: "flight",
        from: "北京首都机场",
        to: "成都天府机场",
        departure: "07:30",
        arrival: "10:40",
        duration: "3小时10分",
        name: "CA1419",
        price: "¥960",
      },
    ],
    totalDuration: "3小时10分",
    totalPrice: "¥960",
    tags: ["飞机"],
  },
  {
    id: "bj-xian-1",
    fromCity: "北京",
    toCity: "西安",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "北京西站",
        to: "西安北站",
        departure: "07:00",
        arrival: "11:12",
        duration: "4小时12分",
        name: "G651 复兴号",
        price: "¥515",
      },
    ],
    totalDuration: "4小时12分",
    totalPrice: "¥515",
    tags: ["高铁直达"],
  },
  {
    id: "bj-wh-1",
    fromCity: "北京",
    toCity: "武汉",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "北京西站",
        to: "武汉站",
        departure: "07:00",
        arrival: "11:24",
        duration: "4小时24分",
        name: "G51 复兴号",
        price: "¥520",
      },
    ],
    totalDuration: "4小时24分",
    totalPrice: "¥520",
    tags: ["高铁直达"],
  },
  {
    id: "bj-tj-1",
    fromCity: "北京",
    toCity: "天津",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "北京南站",
        to: "天津站",
        departure: "07:00",
        arrival: "07:32",
        duration: "32分",
        name: "C2001",
        price: "¥54.5",
      },
    ],
    totalDuration: "32分",
    totalPrice: "¥54.5",
    tags: ["城际高铁", "最快"],
  },
  {
    id: "sh-gz-1",
    fromCity: "上海",
    toCity: "广州",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "上海虹桥站",
        to: "广州南站",
        departure: "06:36",
        arrival: "14:53",
        duration: "8小时17分",
        name: "G817 复兴号",
        price: "¥858",
      },
    ],
    totalDuration: "8小时17分",
    totalPrice: "¥858",
    tags: ["高铁直达"],
  },
  {
    id: "sh-gz-2",
    fromCity: "上海",
    toCity: "广州",
    type: "direct",
    segments: [
      {
        type: "flight",
        from: "上海虹桥机场",
        to: "广州白云机场",
        departure: "07:00",
        arrival: "09:35",
        duration: "2小时35分",
        name: "MU5311",
        price: "¥780",
      },
    ],
    totalDuration: "2小时35分",
    totalPrice: "¥780",
    tags: ["飞机", "最快"],
  },
  {
    id: "sh-sz-1",
    fromCity: "上海",
    toCity: "深圳",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "上海虹桥站",
        to: "深圳北站",
        departure: "06:47",
        arrival: "14:48",
        duration: "8小时01分",
        name: "G278",
        price: "¥830",
      },
    ],
    totalDuration: "8小时01分",
    totalPrice: "¥830",
    tags: ["高铁直达"],
  },
  {
    id: "sh-hz-1",
    fromCity: "上海",
    toCity: "杭州",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "上海虹桥站",
        to: "杭州东站",
        departure: "06:00",
        arrival: "06:58",
        duration: "58分",
        name: "G7501",
        price: "¥73",
      },
    ],
    totalDuration: "58分",
    totalPrice: "¥73",
    tags: ["高铁直达", "最快"],
  },
  {
    id: "sh-nj-1",
    fromCity: "上海",
    toCity: "南京",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "上海虹桥站",
        to: "南京南站",
        departure: "06:00",
        arrival: "07:31",
        duration: "1小时31分",
        name: "G7002",
        price: "¥134",
      },
    ],
    totalDuration: "1小时31分",
    totalPrice: "¥134",
    tags: ["高铁直达"],
  },
  {
    id: "sh-su-1",
    fromCity: "上海",
    toCity: "苏州",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "上海虹桥站",
        to: "苏州北站",
        departure: "06:12",
        arrival: "06:39",
        duration: "27分",
        name: "G1202",
        price: "¥34.5",
      },
    ],
    totalDuration: "27分",
    totalPrice: "¥34.5",
    tags: ["高铁直达", "最快"],
  },
  {
    id: "gz-sz-1",
    fromCity: "广州",
    toCity: "深圳",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "广州南站",
        to: "深圳北站",
        departure: "06:30",
        arrival: "07:10",
        duration: "40分",
        name: "G6201",
        price: "¥75",
      },
    ],
    totalDuration: "40分",
    totalPrice: "¥75",
    tags: ["高铁直达", "最快"],
  },
  {
    id: "gz-sz-2",
    fromCity: "广州",
    toCity: "深圳",
    type: "direct",
    segments: [
      {
        type: "bus",
        from: "广州天河客运站",
        to: "深圳福田汽车站",
        departure: "07:00",
        arrival: "09:00",
        duration: "2小时",
        name: "城际快巴",
        price: "¥60",
      },
    ],
    totalDuration: "2小时",
    totalPrice: "¥60",
    tags: ["城际巴士", "经济"],
  },
  {
    id: "gz-cd-1",
    fromCity: "广州",
    toCity: "成都",
    type: "direct",
    segments: [
      {
        type: "flight",
        from: "广州白云机场",
        to: "成都天府机场",
        departure: "08:00",
        arrival: "11:10",
        duration: "3小时10分",
        name: "3U8732",
        price: "¥920",
      },
    ],
    totalDuration: "3小时10分",
    totalPrice: "¥920",
    tags: ["飞机"],
  },
  {
    id: "gz-xian-1",
    fromCity: "广州",
    toCity: "西安",
    type: "direct",
    segments: [
      {
        type: "flight",
        from: "广州白云机场",
        to: "西安咸阳机场",
        departure: "07:30",
        arrival: "10:35",
        duration: "3小时05分",
        name: "CZ3219",
        price: "¥860",
      },
    ],
    totalDuration: "3小时05分",
    totalPrice: "¥860",
    tags: ["飞机"],
  },
  {
    id: "sz-cd-1",
    fromCity: "深圳",
    toCity: "成都",
    type: "direct",
    segments: [
      {
        type: "flight",
        from: "深圳宝安机场",
        to: "成都天府机场",
        departure: "07:30",
        arrival: "10:40",
        duration: "3小时10分",
        name: "3U8766",
        price: "¥980",
      },
    ],
    totalDuration: "3小时10分",
    totalPrice: "¥980",
    tags: ["飞机"],
  },
  {
    id: "sz-hz-1",
    fromCity: "深圳",
    toCity: "杭州",
    type: "direct",
    segments: [
      {
        type: "flight",
        from: "深圳宝安机场",
        to: "杭州萧山机场",
        departure: "08:00",
        arrival: "10:20",
        duration: "2小时20分",
        name: "CA1736",
        price: "¥820",
      },
    ],
    totalDuration: "2小时20分",
    totalPrice: "¥820",
    tags: ["飞机"],
  },
  {
    id: "cd-cq-1",
    fromCity: "成都",
    toCity: "重庆",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "成都东站",
        to: "重庆北站",
        departure: "06:30",
        arrival: "08:10",
        duration: "1小时40分",
        name: "G8601",
        price: "¥154",
      },
    ],
    totalDuration: "1小时40分",
    totalPrice: "¥154",
    tags: ["高铁直达"],
  },
  {
    id: "cd-cq-2",
    fromCity: "成都",
    toCity: "重庆",
    type: "direct",
    segments: [
      {
        type: "bus",
        from: "成都东站汽车站",
        to: "重庆龙头寺汽车站",
        departure: "07:00",
        arrival: "10:00",
        duration: "3小时",
        name: "成渝快巴",
        price: "¥80",
      },
    ],
    totalDuration: "3小时",
    totalPrice: "¥80",
    tags: ["城际巴士", "经济"],
  },
  {
    id: "cd-xian-1",
    fromCity: "成都",
    toCity: "西安",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "成都东站",
        to: "西安北站",
        departure: "06:30",
        arrival: "10:02",
        duration: "3小时32分",
        name: "G8794",
        price: "¥263",
      },
    ],
    totalDuration: "3小时32分",
    totalPrice: "¥263",
    tags: ["高铁直达"],
  },
  {
    id: "hz-nj-1",
    fromCity: "杭州",
    toCity: "南京",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "杭州东站",
        to: "南京南站",
        departure: "06:00",
        arrival: "07:38",
        duration: "1小时38分",
        name: "G7602",
        price: "¥117",
      },
    ],
    totalDuration: "1小时38分",
    totalPrice: "¥117",
    tags: ["高铁直达"],
  },
  {
    id: "hz-su-1",
    fromCity: "杭州",
    toCity: "苏州",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "杭州东站",
        to: "苏州北站",
        departure: "06:00",
        arrival: "07:05",
        duration: "1小时05分",
        name: "G7504",
        price: "¥65",
      },
    ],
    totalDuration: "1小时05分",
    totalPrice: "¥65",
    tags: ["高铁直达"],
  },
  {
    id: "wh-cd-1",
    fromCity: "武汉",
    toCity: "成都",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "武汉站",
        to: "成都东站",
        departure: "07:00",
        arrival: "12:17",
        duration: "5小时17分",
        name: "G358",
        price: "¥452",
      },
    ],
    totalDuration: "5小时17分",
    totalPrice: "¥452",
    tags: ["高铁直达"],
  },
  {
    id: "wh-gz-1",
    fromCity: "武汉",
    toCity: "广州",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "武汉站",
        to: "广州南站",
        departure: "07:00",
        arrival: "11:10",
        duration: "4小时10分",
        name: "G87",
        price: "¥463",
      },
    ],
    totalDuration: "4小时10分",
    totalPrice: "¥463",
    tags: ["高铁直达"],
  },
  {
    id: "xian-cd-1",
    fromCity: "西安",
    toCity: "成都",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "西安北站",
        to: "成都东站",
        departure: "06:30",
        arrival: "10:02",
        duration: "3小时32分",
        name: "G8791",
        price: "¥263",
      },
    ],
    totalDuration: "3小时32分",
    totalPrice: "¥263",
    tags: ["高铁直达"],
  },
  {
    id: "cs-gz-1",
    fromCity: "长沙",
    toCity: "广州",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "长沙南站",
        to: "广州南站",
        departure: "07:00",
        arrival: "09:30",
        duration: "2小时30分",
        name: "G1001",
        price: "¥314",
      },
    ],
    totalDuration: "2小时30分",
    totalPrice: "¥314",
    tags: ["高铁直达"],
  },
  {
    id: "zz-bj-1",
    fromCity: "郑州",
    toCity: "北京",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "郑州东站",
        to: "北京西站",
        departure: "07:00",
        arrival: "10:36",
        duration: "3小时36分",
        name: "G558",
        price: "¥309",
      },
    ],
    totalDuration: "3小时36分",
    totalPrice: "¥309",
    tags: ["高铁直达"],
  },
  {
    id: "km-cd-1",
    fromCity: "昆明",
    toCity: "成都",
    type: "direct",
    segments: [
      {
        type: "flight",
        from: "昆明长水机场",
        to: "成都双流机场",
        departure: "07:30",
        arrival: "09:10",
        duration: "1小时40分",
        name: "3U8662",
        price: "¥680",
      },
    ],
    totalDuration: "1小时40分",
    totalPrice: "¥680",
    tags: ["飞机"],
  },
  {
    id: "hrb-bj-1",
    fromCity: "哈尔滨",
    toCity: "北京",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "哈尔滨西站",
        to: "北京南站",
        departure: "07:00",
        arrival: "12:49",
        duration: "5小时49分",
        name: "G902",
        price: "¥542",
      },
    ],
    totalDuration: "5小时49分",
    totalPrice: "¥542",
    tags: ["高铁直达"],
  },
  {
    id: "sy-bj-1",
    fromCity: "沈阳",
    toCity: "北京",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "沈阳北站",
        to: "北京南站",
        departure: "07:00",
        arrival: "11:18",
        duration: "4小时18分",
        name: "G218",
        price: "¥403",
      },
    ],
    totalDuration: "4小时18分",
    totalPrice: "¥403",
    tags: ["高铁直达"],
  },
  {
    id: "qd-bj-1",
    fromCity: "青岛",
    toCity: "北京",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "青岛北站",
        to: "北京南站",
        departure: "06:30",
        arrival: "11:47",
        duration: "5小时17分",
        name: "G104",
        price: "¥335",
      },
    ],
    totalDuration: "5小时17分",
    totalPrice: "¥335",
    tags: ["高铁直达"],
  },
  {
    id: "jn-bj-1",
    fromCity: "济南",
    toCity: "北京",
    type: "direct",
    segments: [
      {
        type: "train",
        from: "济南西站",
        to: "北京南站",
        departure: "07:00",
        arrival: "09:24",
        duration: "2小时24分",
        name: "G106",
        price: "¥184",
      },
    ],
    totalDuration: "2小时24分",
    totalPrice: "¥184",
    tags: ["高铁直达"],
  },
];

// 自动生成反向线路：为每条线路生成返程班次
function generateReturnRoutes(routes: TransitRoute[]): TransitRoute[] {
  return routes.map((r) => ({
    ...r,
    id: `${r.id}-r`,
    fromCity: r.toCity,
    toCity: r.fromCity,
    segments: r.segments.map((s) => ({
      ...s,
      from: s.to,
      to: s.from,
      departure: s.arrival.replace("次日 ", ""),
      arrival: s.departure,
    })),
  }));
}

// 全部线路 = 原始线路 + 反向线路
export const ALL_ROUTES: TransitRoute[] = [
  ...SAMPLE_ROUTES,
  ...generateReturnRoutes(SAMPLE_ROUTES),
];

export const SEGMENT_ICONS: Record<string, string> = {
  train: "🚄",
  bus: "🚌",
  metro: "🚇",
  flight: "✈️",
};

export const SEGMENT_LABELS: Record<string, string> = {
  train: "火车/高铁",
  bus: "长途巴士",
  metro: "地铁/城轨",
  flight: "飞机",
};